### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by countnazgul** [mydgd/QSight-Script2Flow#1]
This is a great extension! Thank you!

Have a couple of questions though:
1. Under what license is the code?
2. Out of curiosity how is the script parsing done? How are you getting the different script sections (like "Preceding load", "Comment", "Load SQL" etc)

**Comment by mydgd** [comment]
1. I added a MIT License.
2.  Parsing is the most difficult part. I am hard coding situation by situation and using mainly regex for detecting statements. For example, for each row I am checking if it contains both IF and THEN. If it contains both, it is categorized as starting of IF statement. There are still situations which hasn't been coded, as I discover something is not working I am adding it to my code.
